name: Needs More Info
description: Checks whether issue has filled issue template fields
inputs:
  github-token:
    description: A GitHub token.
    required: false
    default: ${{ github.token }}

  needs-more-info-label:
    description: Name of the 'needs-more-info' label used in the repo
    required: true
    default: needs-more-info

  required-sections:
    description: List of names of required sections
    required: true

  needs-more-info-response:
    description: Start of GitHub Actions response when not enough information is provided
    required: true

runs:
  using: node12
  main: './index.js'
