name: Needs More Info
description: Checks whether the issue template fields are filled
inputs:
  github-token:
    description: A GitHub token.
    required: false
    default: ${{ github.token }}

  needs-more-info-label:
    description: Name of the 'needs-more-info' label used in the repo
    required: true
    default: needs-more-info

  required-sections:
    description: Semicolon separated list of names of required sections eg. 'Description;Reproduction;Platform'
    required: true

  needs-more-info-response:
    description: Start of GitHub Actions response when not enough information is provided
    required: true

runs:
  using: node16
  main: index.js
