name: Close when stale
description: Closes the issue after the specified time if it has the specified label
inputs:
  github-token:
    description: A GitHub token.
    required: false
    default: ${{ github.token }}

  close-when-stale-label:
    description: Label which indicates which issues are considered to be closed
    required: true

  days-to-close:
    description: How many days will have to pass without activity in order to close the issue
    required: true

runs:
  using: node16
  main: index.js
